# 应用名称
spring:
  application:
    name: FDPlatform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/fabric?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: wmlszh
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
    timeout: 1800000 # 连接超时时间（毫秒）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      properties:
        linger:
          ms: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      properties:
        group:
          id: defaultConsumerGroup
        session:
          timeout:
            ms: 120000
        request:
          timeout:
            ms: 120000
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 50
    listener:
      missing-topics-fatal: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.fdplatform.model.domain
  type-handlers-package: org.example.fdplatform.typehandler

server:
  port: 8000



